### ISSUE TITLE
Static analysis

### ISSUE THREAD

**Issue by davegaeddert** [dependencies-io/collector-java-maven#2]
@qoomon I'm thinking about enabling some kind of static analysis (probably just through CodeClimate) so that we can have some basic things checked automatically. That way we can all be on the same page when contributing to this repo and follow some basic style guidelines.

Any objections to this? https://docs.codeclimate.com/docs/sonar-java

They have a couple others too:
- https://docs.codeclimate.com/docs/checkstyle
- https://docs.codeclimate.com/docs/pmd

**Comment by qoomon** [comment]
sounds good to me
